### ISSUE TITLE
有数据库脚本吗？

### ISSUE THREAD

**Issue by getideas** [anselleeyy/logistics-back#1]
有数据库脚本吗？

**Comment by lixiaoyang1216** [comment]
同求，要有初始化数据就好了

**Comment by anselleeyy** [comment]
最近比较忙，初始化的sql数据已经更新，在sql目录下，可登录admin用户，密码：123456
> ps：这个项目当时架构不太好，会在后面放上来一个新的项目（基于SpringBoot2.0 + SpringCloud）

**Comment by lixiaoyang1216** [comment]
补充一点：sql脚本中user表的字段名loginId应改为login_id;
另外，可否再提供下function表的初始数据，现在登录进去后没有菜单可供预览。

**Comment by lixiaoyang1216** [comment]
新的项目（基于SpringBoot2.0 + SpringCloud）跟物流管理系统有关么？还是别的其他系统？
最近在熟悉SpringBoot，刚好也想搭建一个物流信息平台相关的系统，可以借鉴学习一下。

**Comment by anselleeyy** [comment]
暂时还没想好，应该不会是物流系统，接下来的系统是打算做毕业设计的，可能会是一个商城或者是音乐类的软件\(^o^)/
> 另外，sql 脚本我会在下午重新看一下，更新一个新的

**Comment by anselleeyy** [comment]
数据库脚本已经更新，并修复两处bug，项目可登录账号后运行，账号详情请见 README。

**Comment by lixiaoyang1216** [comment]
我也在准备毕设，选题就是物流相关的系统。你的毕设还没选题吗？
